name = "tactic-programming-beginner-guide"
version = "0.2.0"
keywords = ["tutorial"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[lean_lib]]
name = "TutorialAux"

[[require]]
name = "Qq"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"
